# Programming for Data Science (Python)

## In this session, we will learn:
<p>•	Strings and pattern match</p>
<p>•	Numpy</p>

In [47]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Useful string functions

In [ ]:
# isX to validate input


In [18]:
#join() vs split()


'apple, banana, citrus, dragonfruit'

False

### Regular expressions

In [23]:
#Find phone number in the format of XXX-XXX-XXXX


True

In [25]:
# To find phone numbers in a string using the isPhoneNumber function

message = "Call me at 415-555-1011 tomorrow. 415-555-9999 is my office."


['415-555-1011', '415-555-9999']


In [35]:
#Using regular expressions


['415-555-1011', '415-555-9999']

In [ ]:
#What about a phone number formatted like 415.555.4242?


In [42]:
# '.' as wildcard character


['cat', 'hat', 'sat', 'lat', 'mat']

In [31]:
#or (415) 555-4242?


'(415) 555-4242'

In [32]:
# if the area code is optional


'555-4242'

[('415', '555', '4242'), ('415', '555', '9999')]

In [ ]:
#create a tuple

#tuples are immutable, so you can not add new elements
#using merge of tuples with the + operator you can add an element and it will create a new tuple

#adding items in a specific index

#converting the tuple to list
 
#use different ways to add items in list

#convert tuple to a string


In [36]:
#Create a new empty set 

#Create a non empty set

#to add elements to a set
#A new empty set


#Add multiple items


set()
{0, 1, 2, 3, 4}
0
1
2
3
4


In [37]:
#back to regular expression. '+' matches one or more times. '*' matches zero or more times
#\d for digits, \s for space, \w for letter, digit or the underscore

xmasRegex.findall('12 drummers, 11 pipers, 10 lords, 9 ladies, 8 maids, 7 swans, 6 geese, 5 rings, 4 birds, 3 hens, 2 doves, 1 partridge')

['12 drummers',
 '11 pipers',
 '10 lords',
 '9 ladies',
 '8 maids',
 '7 swans',
 '6 geese',
 '5 rings',
 '4 birds',
 '3 hens',
 '2 doves',
 '1 partridge']

In [48]:
#Match everything with (.*)


mo = nameRegex.search('First Name: Al Last Name: Sweigart')


'Al'

'Sweigart'

'First Name: Al Last Name: Sweigart'

In [49]:
#re.I to make regex case-insensitive

robocop.search('Robocop is part man, part machine, all cop.').group()

'Robocop'

In [50]:
#sub() to substitute the searched pattern

namesRegex.sub('CENSORED', 'Agent Alice gave the secret documents to Agent Bob.')

'CENSORED gave the secret documents to CENSORED.'

In [53]:
#re.VERBOSE to ignore comments and whitespace
phoneRegex1 = re.compile(r'((\d{3}|\(\d{3}\))?(\s|-|\.)?\d{3}(\s|-|\.)\d{4}(\s*(ext|x|ext.)\s*\d{2,5})?)')


'415-555-1011'

In [54]:
phoneRegex = re.compile(r'''(
                # area code
                # separator
                # first 3 digits
                # separator
                # last 4 digits
                # extension
    )''', re.VERBOSE)

'415-555-1011'

In [ ]:
#create an email regex


<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create Rank 1 numpy arrays:
</p>

numpy.ndarray

In [63]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)

# because this is a 1-rank array, we need only one index to accesss each element
 
# ndarrays are mutable, here we change an element of the array


(3,)

888 33 333
[888  33 333]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [64]:
# Create a rank 2 array


[[11 12 13]
 [21 22 23]]


(2, 3)

11

12

21

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

There are many way to create numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [65]:
# create a 2x2 array of zeros

# create a 2x2 array filled with 9.0

# create an array of ones


[[0. 0.]
 [0. 0.]]
[[9. 9.]
 [9. 9.]]
[[1. 1.]]


In [ ]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array

# which means we need to use two indexes to access an element


In [66]:
# create an array of random floats between 0 and 1


[[0.11876339 0.21795967]
 [0.75529681 0.60944316]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [ ]:
# Rank 2 array of shape (3, 4)

#Use array slicing to get a subarray consisting of 2 rows x 2 columns.

#When you modify a slice, you actually modify the underlying array.


In [ ]:
# Using both integer indexing & slicing generates an array of lower rank


# Slicing alone: generates an array of the same rank as the an_array

#We can do the same thing for columns of an array:
